services:
  - type: web
    name: hrone-attendance-service
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node scripts/cloud-start.js
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DB
        value: test
      - key: TZ
        value: Asia/Kolkata
      - key: PORT
        value: 10000
